### ISSUE TITLE
Unable to exit normally

### ISSUE THREAD

**Issue by misterDu233** [lx200916/desktop_lyrics_plugin#1]
Hello, the program runs under windows11. After closing cider, the lyrics will still be displayed on the desktop. I hope it can be solved later

**Comment by lx200916** [comment]
Might Fix.Try the newest commit,

**Comment by misterDu233** [comment]
I tried to pull the project again in cider, but the prompt failed. Is this my cider's error

**Comment by lx200916** [comment]
Sorry Idk...The whole plugin system seems buggy...Maybe try `git pull` from plugin directory or even just overwrite files.

U can locate the cider directory from `Cider Settings-Advanced-Debug-Open Cider Folder` and navigate to `Plugins` folder.

**Comment by misterDu233** [comment]
OK, I have just tested the normal exit. Thank you for your reply

**Comment by lx200916** [comment]
Marked as Fixed.
