### ISSUE TITLE
Feature request: Automatically hide desktop lyrics when no song is playing.

### ISSUE THREAD

**Issue by karllee830** [lx200916/desktop_lyrics_plugin#10]
The current desktop lyrics are a bit cumbersome to hide when you don't listen to a song for a while, and you need to open cider to close it.
Is it possible to add a feature that automatically hides the desktop lyrics when a song is paused or when no song is playing? 
Thank you very much!

以及我看到您的博客是中文的，如果可以的话，我们可以用中文交流 : )

**Comment by lx200916** [comment]
Seems Reasonable & easy to handle.
大概过几周把这个功能加上去,最近考试周有点忙就摸了.

**Comment by karllee830** [comment]
> Seems Reasonable & easy to handle.

Looking forward to it!
很期待您的下一次更新！

**Comment by karllee830** [comment]
另，不知您有没有兴趣将此插件移植到Spotify上。
Spotify上已经有修改扩展系统了 [Spicetify](https://spicetify.app/)。
这是相关的[开发文档](https://spicetify.app/docs/development)。

**Comment by lx200916** [comment]
> 另，不知您有没有兴趣将此插件移植到Spotify上。 Spotify上已经有修改扩展系统了 [Spicetify](https://spicetify.app/)。 这是相关的[开发文档](https://spicetify.app/docs/development)。

我个人不怎么用Sp，但是我印象中已经有比较完善的插件了，比如 Lyricify,从截图上来看大概是可以实现桌面悬浮歌词的目的的。
另外其实这是一个一时兴起的Side Project,代码和程序结构都比较散乱，能做的功能也比较有限，暂时可能不会考虑移植到其他平台。但是本项目的Renderer部分和歌词插件部分是解耦的，你可以参照这个项目里的JavaScript代码，要达到显示文字的效果，实质上只需要向一个进程间管道灌入文字就可以了。所以你自己实现歌词的展示理论上应该也是可以的。
另,渲染部分写在https://github.com/lx200916/desktop_plugin_server ,如果有需要你也可以参考修改渲染器的实现。

**Comment by lx200916** [comment]
Fixed.
