### ISSUE TITLE
[Feature Request] Set default state when starting up.

### ISSUE THREAD

**Issue by bigplayer-ai** [lx200916/desktop_lyrics_plugin#12]
Hey,
Can we set default state when starting up cider?
I want it to open desktop lyrics + follow lyrics as default option on startup.

**Comment by lx200916** [comment]
what does `Default State` mean? By design those settings should be saved and loaded on the next startup.

**Comment by bigplayer-ai** [comment]
oh so I think this is "me" problem or a bug.
For me the settings for desktop lyrics plugin is not saved after restart: Everytime I restart cider/PC, desktop lyrics does not open or follow lyrics (Even though it was set like this before closing cider).

**Comment by lx200916** [comment]
Seems like a bug....will check.

**Comment by lx200916** [comment]
Maybe check the update. Hope it works now.
