### ISSUE TITLE
Doesn’t work now

### ISSUE THREAD

**Issue by oohb** [lx200916/desktop_lyrics_plugin#14]
Hi
i've downloaded the github-source Cider, and the addon from Cider-Setting. However, now the lyrics doesn't show up on the desktop. Wonder if it is a bug or something else wrong.
I've tried click "addons-open desktop lyrics" and "addons-Enable follow lyrics panel", but still not working.
Looking forward to the solution, and thanks for the extraordinary addon.
你好，
我在G站源下载了Cider，并且在Cider的设置-插件中下载了您开发的桌面歌词插件，但不知是否是由于个人bug或是我的设置并不完全，桌面歌词并未成功启动。
尝试过在插件中反复激活桌面歌词或跟随。。，均未能作用。希望能得到您的回复，感谢您开发的如此棒的插件：）

**Comment by lx200916** [comment]
Please attach more info about your enviorment:
1. Your System version? Only Win11&quite last versions of Win10 fully tested.
2. Check if `default-config.toml` exists in `%APPDATA%/Cider Desktop Plugin/config`,and attach its content.
3. Check if `%APPDATA%\Cider\Plugins\gh_*(a numberic string)\plugin.log` exists and attach it too.
4. Check if any process named `untitled13.exe` running in Task Manager.

**Comment by oohb** [comment]
> Please attach more info about your enviorment:
> 
> 1. Your System version? Only Win11&quite last versions of Win10 fully tested.
> 2. Check if `default-config.toml` exists in `%APPDATA%/Cider Desktop Plugin/config`,and attach its content.
> 3. Check if `%APPDATA%\Cider\Plugins\gh_*(a numberic string)\plugin.log` exists and attach it too.
> 4. Check if any process named `untitled13.exe` running in Task Manager.

---
1. It's a win11(beta) laptop, the OS version is 22623.1095.
2. Yes, it exists.
![image](https://user-images.githubusercontent.com/122853676/212819454-938b9d71-0b5b-46f2-ad20-68f96f8b77cf.png)
3. No, there is no file named 'plugin.log'.
![image](https://user-images.githubusercontent.com/122853676/212819708-89020221-e840-449e-b8af-5b0a13769251.png)
4. No, it's not running.
![image](https://user-images.githubusercontent.com/122853676/212819802-7c4fd142-6841-44b8-bc3c-bb1f04aa794c.png)

**Comment by lx200916** [comment]
Sad...It seems plugin fails to bring up the renderer process. Please check 2 other things:
1. run `untitled13.exe` manually. (by command-line to capture any errors)
2. check if any javascript errors in Cider logs( located in  %APPDATA%\Cider\logs)

**Comment by oohb** [comment]
> Sad...It seems plugin fails to bring up the renderer process. Please check 2 other things:
> 
> 1. run `untitled13.exe` manually. (by command-line to capture any errors)
> 2. check if any javascript errors in Cider logs( located in  %APPDATA%\Cider\logs)

---
1. The .exe file can be run, but i can't type any words to the input line.
![image](https://user-images.githubusercontent.com/122853676/212824587-bf71d209-63c3-4ec3-9080-2093158babac.png)
2. There are some errors about 'js' in the main file. Sorry i'm totally a layman so that i can't extract useful imformation.

**Comment by lx200916** [comment]
Uh...This is so weird. The renderer was brought up but failed to connect. You can run `untitled13.exe` manually and then run Cider, untitled13.exe should print `connected` if everything fine.
PS :untitled13.exe nerver reads std-in, so any input will receive no response.


> > Sad...It seems plugin fails to bring up the renderer process. Please check 2 other things:
> > 
> > 1. run `untitled13.exe` manually. (by command-line to capture any errors)
> > 2. check if any javascript errors in Cider logs( located in  %APPDATA%\Cider\logs)
> 
> 1. The .exe file can be run, but i can't type any words to the input line.
>    ![image](https://user-images.githubusercontent.com/122853676/212824587-bf71d209-63c3-4ec3-9080-2093158babac.png)
> 2. There are some errors about 'js' in the main file. Sorry i'm totally a layman so that i can't extract useful imformation.

**Comment by lx200916** [comment]
PPS: To be honest, `Pipe fail to connect` case is really really rare...if test above does no work, try those Powershell commands after `untitled13.exe` started.
```powershell
$pipe = new-object System.IO.Pipes.NamedPipeClientStream '.','lyrics_pipe','Out'
$pipe.Connect()
$sw = new-object System.IO.StreamWriter $pipe
$sw.Write("111")
$sw.Flush()
```
Renderer should show `111` if everything works fine, or it should throw errors.

**Comment by oohb** [comment]
> Uh...This is so weird. The renderer was brought up but failed to connect. You can run `untitled13.exe` manually and then run Cider, untitled13.exe should print `connected` if everything fine. PS :untitled13.exe nerver reads std-in, so any input will receive no response.
> 
> > > Sad...It seems plugin fails to bring up the renderer process. Please check 2 other things:
> > > 
> > > 1. run `untitled13.exe` manually. (by command-line to capture any errors)
> > > 2. check if any javascript errors in Cider logs( located in  %APPDATA%\Cider\logs)
> > 
> > 
> > 
> > 1. The .exe file can be run, but i can't type any words to the input line.
> >    ![image](https://user-images.githubusercontent.com/122853676/212824587-bf71d209-63c3-4ec3-9080-2093158babac.png)
> > 2. There are some errors about 'js' in the main file. Sorry i'm totally a layman so that i can't extract useful imformation.
---

When I run it manually, then run cider next, it WORKS! However, if i close **untitled13.exe, the desktop lyrics dispear immediately. It seems that **untitled 13.exe can't silently start and work in the background.

**Comment by lx200916** [comment]
In fact according to the log file you attach,at least 2 times the process was started and printed its pid.
Could you start the Cider without untitled13 and then attach the log file? It is almost impossible that `spawn` failed to create a sub-process...
顺便问一下，如果你是中国区用户的话，有没有使用某些安全软件拦截创建进程的行为呢？虽然我自用的火绒没有这种情形，但是确实存在这种可能。

**Comment by oohb** [comment]
Already tried for seceral times, and the log file is as follow:
Yes, i am using it in Chian. I also utilized huorong as the only one security software on my PC.
已做出几次未启动untitled13文件的Cider启动尝试，现将log文件发您。我是中国区的用户，同样使用火绒作为唯一的安全软件。我在火绒的设置中进行了一系列查找和尝试，并未发现对问题有改善（我已将untitled13文件添加到信任区并重启cider，插件仍然未正常启用）

**Comment by lx200916** [comment]
> Already tried for seceral times, and the log file is as follow: [main.log](https://github.com/lx200916/desktop_lyrics_plugin/files/10436422/main.log) Yes, i am using it in Chian. I also utilized huorong as the only one security software on my PC. 已做出几次未启动untitled13文件的Cider启动尝试，现将log文件发您。我是中国区的用户，同样使用火绒作为唯一的安全软件。我在火绒的设置中进行了一系列查找和尝试，并未发现对问题有改善（我已将untitled13文件添加到信任区并重启cider，插件仍然
未正常启用）

Log shows renderer was brought up....I wrote some debug code so could you please replace the `index.js` with attachment and restart cider then upload the logs?
[index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10436986/index.zip)

**Comment by oohb** [comment]
[main.log](https://github.com/lx200916/desktop_lyrics_plugin/files/10437241/main.log)
Unfornately :(

**Comment by lx200916** [comment]
👌 Seems I got what happened,maybe I add more debug code tomorrow & we can fix it.
晚安好梦～

**Comment by oohb** [comment]
> 👌 Seems I got what happened,maybe I add more debug code tomorrow & we can fix it. 晚安好梦～

Looking forward to that :)   晚安

**Comment by lx200916** [comment]
[index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10441065/index.zip)
Could u replace with this version and upload logs again? I guess the problem is related to do with Windows Powershell and it seems Windows completely change `%CMDSPEC%` from `cmd.exe` to `ps`.

**Comment by oohb** [comment]
> [index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10441065/index.zip) Could u replace with this version and upload logs again? I guess the problem is related to do with Windows Powershell and it seems Windows completely change `%CMDSPEC%` from `cmd.exe` to `ps`.

---
Morning.
I have tried thrice: only Cider firstly, then restart Cider with **untitled 13. exe secondly, and only Cider the third time. The plugin still can't work as expected :(
Yet, I can not find untitled 13 existing in my task manager.
Here is the update log file.
[main.log](https://github.com/lx200916/desktop_lyrics_plugin/files/10441588/main.log)

**Comment by lx200916** [comment]
[index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10442006/index.zip)

Lets try this,hope it fixed.

**Comment by oohb** [comment]
> [index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10442006/index.zip)
> 
> Lets try this,hope it fixed.

---
Sry, busy day.
It works now! Thanks for your time and patience! 
Can't find 'Sponsor', how can i donate a little piece to the project?
It's really an excellent job!

**Comment by lx200916** [comment]
> > [index.zip](https://github.com/lx200916/desktop_lyrics_plugin/files/10442006/index.zip)
> > Lets try this,hope it fixed.
> 
> Sry, busy day. It works now! Thanks for your time and patience! Can't find 'Sponsor', how can i donate a little piece to the project? It's really an excellent job!

Glad it works.
PS. This is only a very side project with casual design, and it has nothing to do with the word "excellent" to be honest. A `star` is the best reward for me. ❤
