### ISSUE TITLE
Lyrics showing IrcInstrumental at the start of songs that don't start immediately

### ISSUE THREAD

**Issue by Supernoww** [lx200916/desktop_lyrics_plugin#16]
Is it supposed to happen ?

[https://imgur.com/a/H3kK0WP](url)

**Comment by lx200916** [comment]
If you means the `IrcInstrumental` behavior, Yes. It is a `placeholder` of lyrics for some pure-music part (Prelude for example). Furthermore, this behavior comes from the lyrics provider, the plugin only render the text exactly `as is`.

P.S. I guess Cider may replace those `placeholder words` to some loading animation, so you may find it different.

**Comment by Supernoww** [comment]
Ok, thanks.
