### ISSUE TITLE
Binary doesn't close after hiding lyrics.

### ISSUE THREAD

**Issue by maxivimax** [lx200916/desktop_lyrics_plugin#2]
Binary doesn't close after hiding lyrics in cider. Maybe this bug is only on my computer, idk, but I reinstall the plugin and cider, after that the problem does not go away.

**Comment by maxivimax** [comment]
https://user-images.githubusercontent.com/53828303/189497795-b88eb17c-60e9-44a0-8c80-99696e0a4ba7.mp4

**Comment by lx200916** [comment]
Hi If U mean `Desktop Lyrics still show up after "Lyrics Panel" hides`,yes it is by design. This plugin is not A PART OF the Lyrics Panel ,it is a standalone one..... So u cant control the Desktop Lyrics by Lyrics Panel for now, sry.

**Comment by maxivimax** [comment]
Okey, thank you for answer

**Comment by lx200916** [comment]
Added A MenuEntry To Follow the panel show/hide behavior.
