### ISSUE TITLE
HOW CAN I CLOSE IF DONT CLOSE CIDER

### ISSUE THREAD

**Issue by CrterBrian** [lx200916/desktop_lyrics_plugin#3]

**Comment by Goldsucher07** [comment]
Would guess to close it with task manger that should work. 
If you know what the error is you can also report it 👍

**Comment by Goldsucher07** [comment]
So you close cider and the lyrics are still there ?

**Comment by CrterBrian** [comment]
> So you close cider and the lyrics are still there ?

is close ,but i want   close it by itshelf and  not close cider when i hear song,and i cant close it in task manger because  i cant find it in task manger

**Comment by lx200916** [comment]
Uh... Sry I am too lazy to add a control button for it. For now U may find a process named 'untitled13.exe' and kill it to close.

**Comment by lx200916** [comment]
> > So you close cider and the lyrics are still there ?
> 
> is close ,but i want close it by itshelf and not close cider when i hear song,and i cant close it in task manger because i cant find it in task manger

A MenuEntry is added so U can control by it.
