### ISSUE TITLE
hey how to use the plugin?

### ISSUE THREAD

**Issue by ghost** [lx200916/desktop_lyrics_plugin#4]
hey how to use the plugin?

**Comment by lx200916** [comment]
install it,then a small float semitransparent window will appear when you play songs. Only support Windows.

**Comment by ghost** [comment]
does not work on windows 11 22h2

**Comment by lx200916** [comment]
> does not work on windows 11 22h2

Uh... I may update my laptop & test it.

**Comment by ghost** [comment]
i am using store version also.
It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?

**Comment by lx200916** [comment]
Okay it turns out that Cider had changed one of its API and this plugin failed to get the PlayBack Time Info. I may commit a fix later.

**Comment by direrFlood** [comment]
> i am using store version also.
> It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?

It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?

**Comment by ghost** [comment]
> Okay it turns out that Cider had changed one of its API and this plugin failed to get the PlayBack Time Info. I may commit a fix later.

It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?

**Comment by lx200916** [comment]
I just push some fix to the repo,maybe try it now.

> It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?
BTW What does `ignore mouse clicks` mean? The lyrics window should be transparent and never respond to any mouse event.

**Comment by ghost** [comment]
> I just push some fix to the repo,maybe try it now.
> 
> > It is still not working for me but can you make it ignore mouse clicks unless a hotkey is pressed?
> > BTW What does `ignore mouse clicks` mean? The lyrics window should be transparent and never respond to any mouse event.

still not working for me
![Clip_20220930_192719](https://user-images.githubusercontent.com/110556802/193315325-b60ad735-0a0e-45dd-99fe-63ace5cfb1c0.png)
i still did not try it to request a feature completely detailed lol. so you can move the windows to second display or something?

**Comment by lx200916** [comment]
That's strange...Could U confirm this is a process named `untitled13.exe` running? Even the old version should render a lyrics window when the `Lyrics Drawer` opens.

**Comment by lx200916** [comment]
BTW the store version app may fail to obtain the permission to run binaries....Maybe try an win32 EXE version?

**Comment by ghost** [comment]
> That's strange...Could U confirm this is a process named `untitled13.exe` running? Even the old version should render a lyrics window when the `Lyrics Drawer` opens.

no there is no untitled13.exe showing in  the task manager.
i did some digging found this untitled 13.exe in plugins folder :
C:\Users\*****\AppData\Local\Packages\27554FireDevElijahKlauman.CiderAlpha_270bejk4xgzqp\LocalCache\Roaming\Cider\Plugins\gh_497959672

**Comment by ghost** [comment]
ok it worked for github version. you need to fix it on the store version.
how can i move it to show on another display? and can you add the "hide/unhide" functionality?

**Comment by lx200916** [comment]
> ok it worked for github version. you need to fix it on the store version.
> how can i move it to show on another display? and can you add the "hide/unhide" functionality?

Uh... Firstly it is almost impossible to fix it on the MS Store version due to restrictions from MS.

I may add 'Hide' functionality later, but 'making the window move to other display' is a much more diffcult job, (I have to rewrite the way it renders, quite tough..) so  for now I wont add it to the feature list.

**Comment by lx200916** [comment]
Added MenuEntry to control Show/Hide Behavior.

**Comment by lx200916** [comment]
Close for now.

**Comment by direrFlood** [comment]
> 

my ocd killing me, when it is open it says "open lyrics"
when it is closed it says "close lurics"

**Comment by lx200916** [comment]
Added MenuEntry to unLock the window so you can drag & reposition it.

**Comment by ghost** [comment]
Man thank you so much! The extension works perfectly<3. only if you can add hot key to move the windows instead of the menu(too much work.)

**Comment by lx200916** [comment]
> Man thank you so much! The extension works perfectly<3. only if you can add hot key to move the windows instead of the menu(too much work.)

Maybe Added later...
