### ISSUE TITLE
[feature request] ability to move the lyrics windows when holding a key.

### ISSUE THREAD

**Issue by ghost** [lx200916/desktop_lyrics_plugin#6]
Hey, It works like that(I am not tech savvy because of that i can't make it but I have the idea).
1) Pressing hotkey(for example shift) -> than the lyrics' windows become movable.

**Comment by lx200916** [comment]
See https://github.com/lx200916/desktop_lyrics_plugin/issues/4#issuecomment-1263824963.

**Comment by lx200916** [comment]
Added MenuEntry to unLock the window so you can drag & reposition it.
