### ISSUE TITLE
[Bug]: this plugin does not work with store version of cider. 

### ISSUE THREAD

**Issue by ghost** [lx200916/desktop_lyrics_plugin#7]
### Describe the Bug

for example this plugin: https://github.com/lx200916/desktop_lyrics_plugin 
works just fine on cider desktop version
when trying it on cider store version it does not work. this is pretty annoying as i paid for the store version thinking i will get better product and stability. turns out the free one is more stable!

### Steps to Reproduce

1. install desktop lyrics plugin on store and desktop versions of cider
2. compare between both. on desktop the plugin works o store version the plugin does not work

### Environment Information

- OS: w11 22h2 
- Desktop Environment: w11 22h2 
- App Version:
- Commit ID:

### How did you download the software?

Microsoft Store

**Comment by lx200916** [comment]
See #4 .
MS restrict UWP apps from running binaries, so... sadly no workaround.
